import { DynamicModule, Module } from '@nestjs/common';
import { StripeCoreModule } from './stripe-core.module';
import { StripeOptions, StripeAsyncOptions } from './interfaces';

/**
 * Import and provide base nestjs-stripe related classes.
 *
 * @module
 */
@Module({})
export class StripeModule {
  /**
   * Import the providers generated by nestjs-stripe core module.
   *
   * @param {StripeOptions} options
   *
   * @returns {DynamicModule}
   */
  static forRoot(options: StripeOptions): DynamicModule {
    return {
      module: StripeModule,
      imports: [StripeCoreModule.forRoot(options)],
    };
  }

  /**
   * Import the providers asynchronously generated by nestjs-stripe core module.
   *
   * @param {StripeAsyncOptions} options
   *
   * @returns {DynamicModule}
   */
  static forRootAsync(options: StripeAsyncOptions): DynamicModule {
    return {
      module: StripeModule,
      imports: [StripeCoreModule.forRootAsync(options)],
    };
  }
}
